# Generated by Django 5.0 on 2024-08-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
