# Generated by Django 5.0 on 2024-08-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowapp', '0002_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimages',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
